apiVersion: apps/v1
kind: Deployment
metadata:
  name: gophertales
  namespace: gophertales
  labels:
    app: gophertales
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gophertales
  template:
    metadata:
      labels:
        app: gophertales
    spec:
      containers:
      - name: gophertales
        image: your-dockerhub-username/gophertales:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: HOST
          value: "0.0.0.0"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: gophertales-secrets
              key: mongo-uri
        - name: DB_NAME
          value: "gophertales"
        - name: STORY_DATA_FILE
          value: "gopher_six.json"

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gophertales-service
  namespace: gophertales
spec:
  selector:
    app: gophertales
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Namespace
metadata:
  name: gophertales
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gophertales-config
  namespace: gophertales
data:

  static-dir: "./static"
  template-dir: "./templates"
---
apiVersion: v1
kind: Secret
metadata:
  name: gophertales-secrets
  namespace: gophertales
type: Opaque
data:
  mongo-uri: bW9uZ29kYitzcnY6Ly91c2VybmFtZTpwYXNzd29yZEBjbHVzdGVyLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk= # Replace with your MongoDB Atlas URI (base64 encoded)